// automatically generated by the FlatBuffers compiler, do not modify

package guideme.flatbuffers.scene;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ExpShaderInfo extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ExpShaderInfo getRootAsExpShaderInfo(ByteBuffer _bb) { return getRootAsExpShaderInfo(_bb, new ExpShaderInfo()); }
  public static ExpShaderInfo getRootAsExpShaderInfo(ByteBuffer _bb, ExpShaderInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ExpShaderInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int lighting() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean mutateLighting(int lighting) { int o = __offset(6); if (o != 0) { bb.put(o + bb_pos, (byte) lighting); return true; } else { return false; } }
  public float alphaTest() { int o = __offset(8); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public boolean mutateAlphaTest(float alpha_test) { int o = __offset(8); if (o != 0) { bb.putFloat(o + bb_pos, alpha_test); return true; } else { return false; } }
  public boolean vertexColor() { int o = __offset(10); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateVertexColor(boolean vertex_color) { int o = __offset(10); if (o != 0) { bb.put(o + bb_pos, (byte)(vertex_color ? 1 : 0)); return true; } else { return false; } }
  public boolean textured() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean mutateTextured(boolean textured) { int o = __offset(12); if (o != 0) { bb.put(o + bb_pos, (byte)(textured ? 1 : 0)); return true; } else { return false; } }

  public static int createExpShaderInfo(FlatBufferBuilder builder,
      int nameOffset,
      int lighting,
      float alphaTest,
      boolean vertexColor,
      boolean textured) {
    builder.startTable(5);
    ExpShaderInfo.addAlphaTest(builder, alphaTest);
    ExpShaderInfo.addName(builder, nameOffset);
    ExpShaderInfo.addTextured(builder, textured);
    ExpShaderInfo.addVertexColor(builder, vertexColor);
    ExpShaderInfo.addLighting(builder, lighting);
    return ExpShaderInfo.endExpShaderInfo(builder);
  }

  public static void startExpShaderInfo(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addLighting(FlatBufferBuilder builder, int lighting) { builder.addByte(1, (byte) lighting, (byte) 0); }
  public static void addAlphaTest(FlatBufferBuilder builder, float alphaTest) { builder.addFloat(2, alphaTest, 0.0f); }
  public static void addVertexColor(FlatBufferBuilder builder, boolean vertexColor) { builder.addBoolean(3, vertexColor, false); }
  public static void addTextured(FlatBufferBuilder builder, boolean textured) { builder.addBoolean(4, textured, false); }
  public static int endExpShaderInfo(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ExpShaderInfo get(int j) { return get(new ExpShaderInfo(), j); }
    public ExpShaderInfo get(ExpShaderInfo obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

