// automatically generated by the FlatBuffers compiler, do not modify

package guideme.flatbuffers.scene;

@SuppressWarnings("unused")
public final class ExpShaderLighting {
  private ExpShaderLighting() { }
  public static final int LIGHTMAP = 0;
  public static final int DIFFUSE = 1;
  public static final int NONE = 2;

  public static final String[] names = { "LIGHTMAP", "DIFFUSE", "NONE", };

  public static String name(int e) { return names[e]; }
}

